### PR TITLE
[!] make recommendation metrics first-class citizens, closes #824

### LINKED ISSUE #824: all recommendations metrics are seen internally as one metric
**Describe the bug**
The `Reap()` method in reaper module, assigns all `reco_*` prefixed metrics the `recoMetricName` const name so if 2 or more `reco_*` metrics are present for certain database, they will be seen as the one `recoMetricName` metric and their cancel functions and metric definitions will interfere 
```
if strings.HasPrefix(metric, recoPrefix) {
	metric = recoMetricName
	metricDefExists = true
}
...
dbMetric := monitoredSource.Name + dbMetricJoinStr + metric ### interfere of dbMetric
_, cancelFuncExists := r.cancelFuncs[dbMetric] ### interfere of cancel functions
```

**Steps to reproduce**
1. run pgwatch and update the webui to use any `reco_*` metric with interval > 0
2. in the logs you will see that the metric name is changed to `recommendations` and interval is 0s.
```
2025-06-30 07:45:29.586 [WARNING] [source:books344] [metric:recommendations] Total fetching time of 92.563µs bigger than 0s interval
```

### PR DESCRIPTION
**Pull request by pashagolub**
- Remove hard-coded recommendations handling from reaper
- Add `metric_storage_name: "recommendations"` to all `reco_` metrics
- Create dedicated `recommendations` preset with distributed intervals
- Update `exhaustive/full` presets to use individual `reco_` metrics
- Add migration to handle existing installations
- Clean up legacy

### CODE REVIEW

File: internal/reaper/recommendations.go
Comment (0xgouda) [inline internal/reaper/recommendations.go:1]: won't it be better to move the remaining special metrics consts definitions to reaper/metric.go and remove this file?
or at least rename it.

File: internal/reaper/reaper.go [hunk 1]
```diff
@@ -146,12 +146,7 @@ func (r *Reaper) Reap(ctx context.Context) {
...
 
-				if strings.HasPrefix(metric, recoPrefix) {
-					metric = recoMetricName
-					metricDefExists = true
-				} else {
-					mvp, metricDefExists = metricDefs.GetMetricDef(metric)
-				}
+				mvp, metricDefExists = metricDefs.GetMetricDef(metric)
 
 				dbMetric := monitoredSource.Name + dbMetricJoinStr + metric
```
Comment (0xgouda) [inline internal/reaper/reaper.go]: can't we now get rid of `metric` and use `metricName` in its place here and in other lines, to avoid confusion in the future?
