### PR TITLE
[-] fix data race in Prometheus sink, fixes #1136

### LINKED ISSUE #1136: Data race in PrometheusWriter(concurrent map iteration/write)
**Describe the bug**

I detected a race condition in the `PrometheusWriter` sink. The `Collect` method iterates over the global `promAsyncMetricCache` map without holding a lock, while metric updates may concurrently arrive via `Write → PromAsyncCacheAddMetricData`. Since the cache is a Go map, this leads to unsynchronized concurrent iteration and mutation.

**To Reproduce**
Run the following test with the race detector enabled:

```
package sinks

import (
	"context"
	"sync"
	"testing"
	"time"

	"github.com/cybertec-postgresql/pgwatch/v5/internal/metrics"
	"github.com/prometheus/client_golang/prometheus"
)

func TestCollect_RaceCondition(t *testing.T) {
	// 1. Initialize the real PrometheusWriter
	// Note: In the current buggy code, this shares the global 'promAsyncMetricCache'
	promw, _ := NewPrometheusWriter(context.Background(), "127.0.0.1:0/pgwatch")

	// 2. Register a metric so Write() actually puts data into the map
	promw.SyncMetric("race_db", "test_metric", AddOp)

	var wg sync.WaitGroup
	done := make(chan struct{})

	// --- The Writer (Simulating Database Updates) ---
	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			select {
			case <-done:
				return
			default:
				// Call the Write method
				promw.Write(metrics.MeasurementEnvelope{
					DBName:     "race_db",
					MetricName: "test_metric",
					Data: metrics.Measurements{
						{
							metrics.EpochColumnName: time.Now().UnixNano(),
							"value":                 int64(100),
						},
					},
				})
			}
		}
	}()

	// --- The Collector (Simulating Prometheus Scrapes) ---
	wg.Add(1)
	go func() {
		defer wg.Done()
		ch := make(chan prometheus.Metric, 10000)

		for i := 0; i < 50; i++ {
			promw.Collect(ch)

			// Drain the channel so it doesn't block
		drainLoop:
			for {
				select {
				case <-ch:
				default:
					break drainLoop
				}
			}
		}
		close(done)
	}()

	wg.Wait()
}
```

**Expected behavior**

Concurrent calls to `Write()` and `Collect()` should be thread-safe and not have a data race.

**Actual behavior**

```
WARNING: DATA RACE
Read at ... by goroutine 31:
  runtime.mapIterStart()
  .../internal/sinks/prometheus.go:171

Previous write at ... by goroutine 30:
  runtime.mapaccess2_faststr()
  .../internal/sinks/prometheus.go:119
testing.go:1617: race detected during execution of test


```

### PR DESCRIPTION
**Pull request by abhijeetsharma200**
Fixes #1136. 

Will add the test as part of the PR to add tests to prometheus.go

### CODE REVIEW

File: internal/sinks/prometheus.go [hunk 1]
```diff
@@ -159,15 +159,28 @@ func (promw *PrometheusWriter) Collect(ch chan<- prometheus.Metric) {
...
 	if len(promAsyncMetricCache) == 0 {
+		promAsyncMetricCacheLock.Unlock()
 		promw.logger.Warning("No dbs configured for monitoring. Check config")
 		ch <- promw.totalScrapeFailures
 		promw.lastScrapeErrors.Set(0)
 		ch <- promw.lastScrapeErrors
 		return
 	}
+
+	snapshot := promAsyncMetricCache
```
Comment (pashagolub) [inline internal/sinks/prometheus.go:172]: I'd prefer to have a longer lock rather than duplicating metric cache that might be huge on high loaded systems

Comment (abhijeetsharma200) [reply internal/sinks/prometheus.go:172]: It's not a deep copy; just a pointer swap (O(1), which is 8/4 bytes depending on OS). The map data stays in place, we just change which pointer the global variable holds. After processing, the old map gets garbage collected. New writes go to the fresh map and get picked up on the next scrape. There shouldn't be any data loss because prometheus is scraping periodically

Comment (abhijeetsharma200) [reply internal/sinks/prometheus.go:172]: Also, I noticed `promAsyncMetricCache` is a package-level global rather than a field on the PrometheusWriter struct. Is there a specific reason for that design? Just curious if multiple writer instances are expected to share the cache intentionally

Comment (pashagolub) [reply internal/sinks/prometheus.go:172]: old design. should be a part of a struct actually

**Comment by abhijeetsharma200** [comment]
@pashagolub ping for review

**Comment by pashagolub** [comment]
Could you please add a test case that must fail before the change and is working now. Thanks

**Comment by abhijeetsharma200** [comment]
> Could you please add a test case that must fail before the change and is working now. Thanks

Done! Please let me know if there any additional changes necessary

File: internal/sinks/prometheus.go (hunk 1 above)
Comment (abhijeetsharma200) [reply internal/sinks/prometheus.go:172]: > old design. should be a part of a struct actually

I see, can I then open an issue to refactor it and make it part of a struct?

**Comment by pashagolub** [comment]
Thanks!

**Comment by abhijeetsharma200** [comment]
> old design. should be a part of a struct actually

I see, can I then open an issue to refactor it and make it part of a struct?

**Comment by pashagolub** [comment]
absolutely. be my guest! :-)
