### PR TITLE
[-] only create time partitions if needed

### LINKED ISSUE #1126: pgwatch creates 4 new partitions each time it starts.
**Describe the bug**
pgwatch creates 4 new partitions each time it gets restarted even if those partitions are not needed (locally i have partitions up to July 2026)

**To Reproduce**
1. Run pgwatch
2. Stop pgwatch
3. Check the number of partitions for any metric table
4. Repeat and observe the change by 4 each time

**Expected behavior**
Partitions should be created only if needed, or at most 3 partitions in the future.

**Screenshots**
partitions for source, I just ran a few minutes ago, but had to restart many times:
```
 subpartitions."archiver_pending_count_omdb.test_20260112"         | 2026-01-19 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260119"         | 2026-01-26 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260126"         | 2026-02-02 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260202"         | 2026-02-09 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260209"         | 2026-02-16 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260216"         | 2026-02-23 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260223"         | 2026-03-02 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260302"         | 2026-03-09 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260309"         | 2026-03-16 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260316"         | 2026-03-23 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260323"         | 2026-03-30 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260330"         | 2026-04-06 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260406"         | 2026-04-13 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260413"         | 2026-04-20 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260420"         | 2026-04-27 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260427"         | 2026-05-04 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260504"         | 2026-05-11 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260511"         | 2026-05-18 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260518"         | 2026-05-25 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260525"         | 2026-06-01 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260601"         | 2026-06-08 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260608"         | 2026-06-15 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260615"         | 2026-06-22 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260622"         | 2026-06-29 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260629"         | 2026-07-06 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260706"         | 2026-07-13 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260713"         | 2026-07-20 00:00:00
 subpartitions."archiver_pending_count_omdb.test_20260720"         | 2026-07-27 00:00:00
```

### PR DESCRIPTION
**Pull request by 0xgouda**
- Check if the needed time partition already exists before creating new partitions in postgres sink

TODO:
- [x] Add tests
- [ ] Ensure a migration exists for the changes

Closes #1126

### CODE REVIEW

File: internal/sinks/sql/ensure_partition_postgres.sql [hunk 1]
```diff
@@ -119,6 +119,8 @@ BEGIN
           IF metric_timestamp >= l_part_start AND metric_timestamp < l_part_end THEN
               part_available_from := l_part_start;
               part_available_to := l_part_end;
+          ELSEIF metric_timestamp < l_part_start THEN
+              EXIT; -- No need to create further partitions
           END IF;
```
Comment (0xgouda) [inline internal/sinks/sql/ensure_partition_postgres.sql:124]: The added condition returns and avoids creating additional partitions if we already have the required partition and at least 1 more pre-created partition after it.

However, this now results in the assumption that the opposing `flush(msgs)` metrics won't have an upper bound timestamp > partitions_upper_bound, or this will cause a bug having no time partitions for these rows.

@pashagolub, what do you think? Can we trust this assumption?

Comment (0xgouda) [reply internal/sinks/sql/ensure_partition_postgres.sql:124]: If a user has `--partition-interval` >= `--batching-delay`, that might trigger this bug, but that's a very werid choice.

and btw the current implementation assumes that a single `flush(msgs)` should fit inside `8` partitions at most (the maximum number of partitions that would be created by a single call to `EnsureMetricDbnameTime()`)

Comment (pashagolub) [reply internal/sinks/sql/ensure_partition_postgres.sql:124]: flush() always checks if there are partiotions pre-created, AFAIR

```go
	switch pgw.metricSchema {
	case DbStorageSchemaPostgres:
		err = pgw.EnsureMetricDbnameTime(pgPartBoundsDbName, forceRecreatePartitions)
	case DbStorageSchemaTimescale:
		err = pgw.EnsureMetricTimescale(pgPartBounds)
```

So partiotions are created on demand

Comment (pashagolub) [reply internal/sinks/sql/ensure_partition_postgres.sql:124]: That said, it's safe to assume your statement. But we also may add test to cover that case and check :)

Comment (0xgouda) [reply internal/sinks/sql/ensure_partition_postgres.sql:124]: These lines are the main source of the issue. Please look at #1126, they create 4 new partitions each time pgwatch restarts, also i explained in the `Additional Context` section why they gradually cause more than 3 partitions to be pre-created even without a restart.

File: internal/sinks/postgres.go [hunk 2]
```diff
@@ -202,6 +202,13 @@ var (
 	partitionMapMetricDbname = make(map[string]map[string]ExistingPartitionInfo) // metric[dbname = min/max bounds]
 )
 
+// ResetPartitionCache clears the partition cache 
+func ResetPartitionCache() {
+	forceRecreatePartitions = false
+	partitionMapMetric = make(map[string]ExistingPartitionInfo)
+	partitionMapMetricDbname = make(map[string]map[string]ExistingPartitionInfo)
+}
```
Comment (pashagolub) [inline internal/sinks/postgres.go]: I see what you're doing here! :)
We don't want global functions in production code used only in tests. I understand why you did this. 
I believe it's time to move 
```go
forceRecreatePartitions 
partitionMapMetric      
partitionMapMetricDbname
```
inside `PostgresWriter`, so every time you re-create the writer, it will create partition-related things and nullify those.

**Review by pashagolub — CHANGES_REQUESTED** [review]

File: internal/sinks/postgres.go (hunk 2 above)
Comment (0xgouda) [reply internal/sinks/postgres.go]: done, please re-review

File: internal/sinks/postgres.go [hunk 3]
```diff
@@ -415,13 +415,13 @@ func (pgw *PostgresWriter) flush(msgs []metrics.MeasurementEnvelope) {
 
 	switch pgw.metricSchema {
 	case DbStorageSchemaPostgres:
-		err = pgw.EnsureMetricDbnameTime(pgPartBoundsDbName, forceRecreatePartitions)
+		err = pgw.EnsureMetricDbnameTime(pgPartBoundsDbName, pgw.forceRecreatePartitions)
```
Comment (pashagolub) [inline internal/sinks/postgres.go]: should we omit the second parameter since it is a pgw field anyway, e.g.


```suggestion
		err = pgw.EnsureMetricDbnameTime(pgPartBoundsDbName)
```
